import '../styles/globals.css';
import { AppProps } from 'next/app';
import Head from 'next/head';
import {
  MantineProvider,
  ColorSchemeProvider,
  useMantineTheme,
  Group,
  AppShell,
  Navbar,
  Header,
  ColorScheme,
} from '@mantine/core';
import { IconSun, IconMoonStars } from '@tabler/icons';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import ColorSwitchIcon from '../components/ColorSwitchIcon';
import { NavigationProgress } from '@mantine/nprogress';

export default function App(props: AppProps) {
  const { Component, pageProps } = props;
  const theme = useMantineTheme();
  const [colorScheme, setColorScheme] = useState<ColorScheme>('dark');
  const toggleColorScheme = (value?: ColorScheme) =>
    setColorScheme(value || (colorScheme === 'dark' ? 'light' : 'dark'));

  return (
    <>
      <Head>
        <title>Page title</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='minimum-scale=1, initial-scale=1, width=device-width' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <ColorSchemeProvider colorScheme={colorScheme} toggleColorScheme={toggleColorScheme}>
        <MantineProvider
          withGlobalStyles
          withNormalizeCSS
          theme={{
            colorScheme,
          }}
        >
          <main>
            <NavigationProgress />
            <AppShell
              navbarOffsetBreakpoint='sm'
              asideOffsetBreakpoint='sm'
              header={
                <Header height={{ base: 50, md: 70 }} p='md'>
                  <Group sx={{ height: '100%' }} px={20} position='apart'>
                    <div>LOGO</div>
                    <ColorSwitchIcon />
                  </Group>
                </Header>
              }
            >
              <Component {...pageProps} />
            </AppShell>
          </main>

          <footer className={styles.footer}>
            <div>Made with 🧡 in Schwäbisch Hall</div>
          </footer>
        </MantineProvider>
      </ColorSchemeProvider>
    </>
  );
}
